name: anime4k
services:
  test:
    image: docker.io/imartemy1524/anime4k:3.0
    build:
      context: .
      dockerfile: ./Dockerfile
    runtime: nvidia
    volumes:
      - ./test.mp4:/home/test.mp4
      - ./out:/home/out
    entrypoint: anime4k
    command: "-i /home/test.mp4 ./out/output.mp4"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu,video,compute,graphics,utility]